/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

/**
 *
 * @author Mason Smith
 */
public class AdminMainGui extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public AdminMainGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        WorkOrder = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        RightMenu = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        WorkInProgress = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        jPanel5 = new javax.swing.JPanel();
        Cards = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Employee = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        Extra = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(960, 540));

        jPanel2.setMinimumSize(new java.awt.Dimension(960, 540));
        jPanel2.setPreferredSize(new java.awt.Dimension(960, 540));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        WorkOrder.setBackground(new java.awt.Color(114, 137, 218));
        WorkOrder.setLayout(new java.awt.CardLayout());

        jLabel1.setBackground(new java.awt.Color(251, 0, 70));
        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WorkOrder");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        WorkOrder.add(jLabel1, "card2");

        jPanel2.add(WorkOrder);

        RightMenu.setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setLayout(new java.awt.GridLayout(0, 1));

        WorkInProgress.setBackground(new java.awt.Color(255, 255, 255));
        WorkInProgress.setLayout(new java.awt.CardLayout());

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label1.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        label1.setText("Work In Progress");
        WorkInProgress.add(label1, "card2");

        jPanel1.add(WorkInProgress);

        jPanel5.setBackground(new java.awt.Color(153, 170, 181));
        jPanel5.setLayout(new java.awt.CardLayout());

        Cards.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        Cards.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cards.setText("Cards");
        jPanel5.add(Cards, "card2");

        jPanel1.add(jPanel5);

        RightMenu.add(jPanel1);

        jPanel3.setLayout(new java.awt.GridLayout(0, 1));

        Employee.setBackground(new java.awt.Color(153, 170, 181));
        Employee.setLayout(new java.awt.CardLayout());

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Employee");
        Employee.add(jLabel2, "card2");

        jPanel3.add(Employee);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new java.awt.CardLayout());

        Extra.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        Extra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Extra.setText("Extra");
        jPanel7.add(Extra, "card2");

        jPanel3.add(jPanel7);

        RightMenu.add(jPanel3);

        jPanel2.add(RightMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 950, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMainGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cards;
    private javax.swing.JPanel Employee;
    private javax.swing.JLabel Extra;
    private javax.swing.JPanel RightMenu;
    private javax.swing.JPanel WorkInProgress;
    private javax.swing.JPanel WorkOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
